# Generated by Django 5.2.1 on 2025-05-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
