# Generated by Django 5.2.1 on 2025-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_produit_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='deals',
            field=models.BooleanField(default=False),
        ),
    ]
