# Generated by Django 5.2.1 on 2025-05-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_produit_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
    ]
